language: sh

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s v1.6.0
  - export PATH="$HOME/.deno/bin:$PATH"

script:
  - deno --version
  - deno run -A --reload --unstable test.ts --recompile 

cache:
  directories:
    - '$HOME/.deno'